apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: adorable-alternative-gopher
  region: eu-north-1

vpc:
  id: vpc-08e3d2732962ad5c4
  securityGroup: sg-090d7e200c105e8fd
  subnets:
    public:
      eu-north-1a:
        id: subnet-07613e47379416728
      eu-north-1b:
        id: subnet-02397e9498244ff99
      eu-north-1c:
        id: subnet-0b19932991a9049f3

managedNodeGroups:
  - name: al2-node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
