apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 195044943221.dkr.ecr.eu-north-1.amazonaws.com/result:8dae287e4edef871e1c1604aa7509c59d4eb5a5e
        name: result
        ports:
        - containerPort: 80
          name: result
