apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: 195044943221.dkr.ecr.eu-north-1.amazonaws.com/worker:8dae287e4edef871e1c1604aa7509c59d4eb5a5e
        name: worker
